apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radar-voluntario-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests/overlays/production
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: radar-voluntario-git