apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seafight-market-bot
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./seafight-market-bot
  prune: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
