apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: memos
  namespace: flux-system
spec:
  suspend: true
  interval: 1m0s
  path: ./memos-oke
  prune: false
  force: false
  sourceRef:
    kind: GitRepository
    name: lag0-fleet-manifests-git
