---
# Source: oci-native-ingress-controller/templates/deployment.yaml
#
# OCI Native Ingress Controller
#
# Copyright (c) 2023 Oracle America, Inc. and its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
#
# Source: oci-native-ingress-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-native-ingress-controller
  namespace: native-ingress-controller-system
  labels:
    helm.sh/chart: oci-native-ingress-controller-1.3.3
    app.kubernetes.io/name: oci-native-ingress-controller
    app.kubernetes.io/instance: oci-native-ingress-controller
    app.kubernetes.io/version: "1.3.3"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oci-native-ingress-controller
      app.kubernetes.io/instance: oci-native-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oci-native-ingress-controller
        app.kubernetes.io/instance: oci-native-ingress-controller
    spec:
      serviceAccountName: oci-native-ingress-controller
      automountServiceAccountToken: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: oci-native-ingress-controller-tls
      securityContext:
        {}
      containers:
        - name: oci-native-ingress-controller
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "ghcr.io/oracle/oci-native-ingress-controller:v1.3.3"
          imagePullPolicy: Always
          args: 
          - --lease-lock-name=oci-native-ingress-controller
          - --lease-lock-namespace=native-ingress-controller-system
          - --authType=user
          - --auth-secret-name=native-ingress-controller-creds
          - --controller-class=oci.oraclecloud.com/native-ingress-controller
          - --compartment-id=ocid1.tenancy.oc1..aaaaaaaaoecb5imn4etm67dmqojtre7m57lluyxudwmoi2cs7umwolhcxtha
          - --subnet-id=ocid1.subnet.oc1.sa-saopaulo-1.aaaaaaaaquavsseio4zgq6fvw5drmrak4uqpnkip5kbrpoj5jhzdr4qpp6tq
          - --cluster-id=ocid1.cluster.oc1.sa-saopaulo-1.aaaaaaaakrtbwcpm2um7tsd4hzhenxih4fesj66jb2r2cogqcc6k4tdw2xtq
          - --metrics-backend=prometheus
          - --metrics-port=2223
          - --v=4
          env:
            - name: OCI_RESOURCE_PRINCIPAL_VERSION
              value: "2.2"
            - name: OCI_RESOURCE_PRINCIPAL_REGION
              value: "sa-saopaulo-1"
            - name: OCI_SDK_DEFAULT_RETRY_ENABLED
              value: "true"
            - name: OCI_GO_SDK_DEBUG
              value: "d"
          ports:
            - name: webhook-server
              containerPort: 9443
              protocol: TCP
            - name: metrics-server
              containerPort: 2223
          resources:
            {}
          volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
      priorityClassName: "system-cluster-critical"
