---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  values:
    installCRDs: true
    controller:
      kind: DaemonSet
      service:
        # loadBalancerIP: '144.22.159.10'
        externalTrafficPolicy: Local
        annotations:
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/subnet: "ocid1.subnet.oc1.sa-saopaulo-1.aaaaaaaaquavsseio4zgq6fvw5drmrak4uqpnkip5kbrpoj5jhzdr4qpp6tq"
          # service.beta.kubernetes.io/oci-load-balancer-shape: flexible
          # service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10
          # service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 10
          service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "All"
          # service.beta.kubernetes.io/oci-load-balancer-backend-protocol: HTTP
    tcp:
      "22": sftp/sftp-server:22