apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
# - cert-manager.yaml
# - cert-manager-webhook-oci.yaml
# - clusterissuer-staging.yaml
# - clusterissuer-production.yaml
- namespace.yaml