# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: seafile
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: ./seafile
#   prune: false
#   force: false
#   sourceRef:
#     kind: GitRepository
#     name: lag0-fleet-manifests-git
