apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- vaults/pessoal/cluster-external-secrets-store.yaml
- vaults/pessoal/cluster-external-secrets.yaml
- vaults/pessoal/sftp-secrets.yaml
- vaults/radar-voluntario/
- namespace.yaml
- secret-token.yaml

# Deploy the repositories
- repositories.yaml

# Deploy the CRDs
- deployment-crds.yaml

# Deploy the operator
- deployment.yaml